### ISSUE TITLE
mt76 driver: multi-function devices don't appear as such to systemd

### ISSUE THREAD

**Issue by johncronan** [nbd168/wireless#12]
I have an MT7915 that presents two logical interfaces for the two different radios, but I notice that the driver doesn't put them on separate functions of one PCI device (maybe because there's not a real bridge?). It looks like this:

```
$ ls /sys/bus/pci/devices/0000\:3b\:00.0/net
wlan0  wlp59s0
```

Systemd assigns the first, `wlp59s0`, using the path-based name, but then the second one tries to assign its name in the same manner and it conflicts, so it has to fall back to `wlan0`. It doesn't really matter whether we have names with suffixes `f0` and `f1` (for multi-function) vs `p0` and `p1` (for multi-port), so I'd suggest setting the netdev phys_port_id attribute to unique values for each interface. According to the systemd docs it knows how to pick up on that. Have I understood all this correctly?

I imagine that users often get cranky when interface names change, but this seems like an expected reason for it to happen, yeah?

**Comment by nbd168** [comment]
The driver is not responsible for managing netdevs and their attributes - that's all handled by the mac80211 stack. What the driver does is register two ieee80211 wiphys on the same PCIe device. There are no separate devices here, because on a PCI level, there is no isolation at all. It really is a single device. The wiphys operate independently from each other, so naturally the auto-created netdevs do so as well.
Even if the driver were to register different devices for the different wiphys, having multiple virtual interfaces on a single wiphy is still supported as well, so probably having different devices does not solve the issue either.
Not sure what the solution is here, and I'm not familiar with what systemd does to netdev names either.

**Comment by johncronan** [comment]
Ah, okay. That's too bad. I'm going to close this and send an email to the MAC80211 maintainer asking about how it might work. I'll post here if I get a response.

**Comment by johncronan** [comment]
Ah, okay. That's too bad. I'm going to close this and send an email to the MAC80211 maintainer asking about how it might work. I'll post here if I get a response.
